In [36]:
import pandas as pd
import numpy as np

df = pd.read_csv("D:\Akshaya\AI training\python_Projects\Learningpython1\customer_churn_ml\data\WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [38]:
df.describe()
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [39]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [40]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [41]:
df = df.dropna()  # as Roes are very few its better to drop them instead of filling them with mean or median or wrong values

In [42]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [43]:
df.drop("customerID", axis=1, inplace=True) # inplace is used to make the change in the original dataframe instead of creating a new one

In [44]:
df["Churn"].value_counts()

Churn
No     5163
Yes    1869
Name: count, dtype: int64

In [45]:
df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})
df["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [46]:
df["Churn"].value_counts(normalize=True) # to get the percentage of churned and non-churned customers to check if the dataset is balanced or not

Churn
0    0.734215
1    0.265785
Name: proportion, dtype: float64

In [47]:
def tenure_group(tenure):
    if tenure <= 12:
        return "0-1 year"
    elif tenure <= 24:
        return "1-2 years"
    elif tenure <= 48:
        return "2-4 years"
    else:
        return "4+ years"

df["tenure_group"] = df["tenure"].apply(tenure_group)# Model understands categories better than raw numbers sometimes
df["tenure_group"].value_counts()

tenure_group
4+ years     2239
0-1 year     2175
2-4 years    1594
1-2 years    1024
Name: count, dtype: int64

In [48]:
df["MonthlyCharges_group"] = pd.qcut(df["MonthlyCharges"], 4, labels=["Low", "Medium", "High", "Very High"])

In [49]:
df["avg_monthly_spend"] = df["TotalCharges"] / (df["tenure"] + 1)

In [50]:
df["Contract"].value_counts()

Contract
Month-to-month    3875
Two year          1685
One year          1472
Name: count, dtype: int64

In [51]:
df["SeniorCitizen"] = df["SeniorCitizen"].astype(int)
df["SeniorCitizen"].value_counts()

SeniorCitizen
0    5890
1    1142
Name: count, dtype: int64

In [52]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group,MonthlyCharges_group,avg_monthly_spend
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0-1 year,Low,14.925000
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,One year,No,Mailed check,56.95,1889.50,0,2-4 years,Medium,53.985714
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,0-1 year,Medium,36.050000
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,2-4 years,Medium,40.016304
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,0-1 year,High,50.550000

In [53]:
df.select_dtypes(include='object').columns

C:\Users\admin\AppData\Local\Temp\ipykernel_14444\3732952691.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'tenure_group'],
      dtype='str')

In [54]:
df = pd.get_dummies(df, drop_first=True)  #one hot encoding for categorical variables and drop_first to avoid dummy variable trap:reference encoding

In [55]:
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,avg_monthly_spend,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,...,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1-2 years,tenure_group_2-4 years,tenure_group_4+ years,MonthlyCharges_group_Medium,MonthlyCharges_group_High,MonthlyCharges_group_Very High
0,0,1,29.85,29.85,0,14.925000,False,True,False,False,...,True,False,True,False,False,False,False,False,False,False
1,0,34,56.95,1889.50,0,53.985714,True,False,False,True,...,False,False,False,True,False,True,False,True,False,False
2,0,2,53.85,108.15,1,36.050000,True,False,False,True,...,True,False,False,True,False,False,False,True,False,False
3,0,45,42.30,1840.75,0,40.016304,True,False,False,False,...,False,False,False,False,False,True,False,True,False,False
4,0,2,70.70,151.65,1,50.550000,False,False,False,True,...,True,False,True,False,False,False,False,False,True,False

In [56]:
from sklearn.model_selection import train_test_split

X = df.drop("Churn", axis=1)
y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y  
) #Stratify ensures that the class distribution remains consistent in both training and testing datasets.”

In [57]:
print("Testing set class distribution:")
y_test.value_counts(normalize=True)
print("Training set class distribution:")
y_train.value_counts(normalize=True)

Testing set class distribution:
Training set class distribution:

Churn
0    0.734222
1    0.265778
Name: proportion, dtype: float64

In [58]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter=1000)

model_lr.fit(X_train, y_train)

d:\Akshaya\AI training\python_Projects\Learningpython1\customer_churn_ml\ccvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [59]:
from sklearn.metrics import classification_report

y_pred = model_lr.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1033
           1       0.65      0.55      0.60       374

    accuracy                           0.80      1407
   macro avg       0.75      0.72      0.73      1407
weighted avg       0.79      0.80      0.80      1407

In [60]:
"""As recall for 1 is 0.55 means Out of 100 customers who actually churn,
model correctly identifies 55
and misses 45 ❌not good enough for a churn prediction model as we want to identify as many potential churners as possible to take proactive measures to retain them."""

'As recall for 1 is 0.55 means Out of 100 customers who actually churn,\nmodel correctly identifies 55\nand misses 45 ❌not good enough for a churn prediction model as we want to identify as many potential churners as possible to take proactive measures to retain them.'

In [61]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators=100, random_state=42)

model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)

print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1033
           1       0.63      0.51      0.56       374

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

In [62]:
""" random forest perofomed worse beacuse Churn dataset is not very large

Random Forest needs more data
Logistic Regression works well on smaller datasets  nad data is not non-linerar
observed that Logistic Regression outperformed Random Forest on this dataset, 
showing that simpler models can sometimes generalize better depending on data characteristics
"""
"""we used default parameter in random forest did not try to tune it to perform best
 first we will try othr model and then try to tune the best one """

'we used default parameter in random forest did not try to tune it to perform best\n first we will try othr model and then try to tune the best one '

In [63]:
from sklearn.ensemble import GradientBoostingClassifier

model_gb = GradientBoostingClassifier()

model_gb.fit(X_train, y_train)

y_pred_gb = model_gb.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_gb))

              precision    recall  f1-score   support

           0       0.84      0.89      0.87      1033
           1       0.64      0.53      0.58       374

    accuracy                           0.80      1407
   macro avg       0.74      0.71      0.72      1407
weighted avg       0.79      0.80      0.79      1407

In [64]:
#as this also did not improve recall we need to change the training startegy 
# instead of using SMOTE we will try to use class weights to give more importance to the minority class (churned customers) 
# during training, which can help improve recall for that class.

In [65]:
model_lr_weighted = LogisticRegression(max_iter=1000, class_weight="balanced")

model_lr_weighted.fit(X_train, y_train)

y_pred_lr_w = model_lr_weighted.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_lr_w))

              precision    recall  f1-score   support

           0       0.90      0.71      0.79      1033
           1       0.49      0.79      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407

d:\Akshaya\AI training\python_Projects\Learningpython1\customer_churn_ml\ccvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [66]:
#By improving recall precision has reduced but in this dataset its ok 
# to churn false churners instaed of loosing revenue by missing potential churners.

In [67]:
import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": model_lr_weighted.coef_[0]
})

feature_importance = feature_importance.sort_values(by="Coefficient", ascending=False)

feature_importance.head(10)

                                  Feature  Coefficient
9          MultipleLines_No phone service     0.565070
11            InternetService_Fiber optic     0.421659
29         PaymentMethod_Electronic check     0.412934
10                      MultipleLines_Yes     0.284913
27                   PaperlessBilling_Yes     0.216851
33                  tenure_group_4+ years     0.191177
0                           SeniorCitizen     0.180654
22                        StreamingTV_Yes     0.112759
28  PaymentMethod_Credit card (automatic)     0.103274
24                    StreamingMovies_Yes     0.083555

In [68]:
#Higher value coeffiecient → higher chance of churn

In [ ]:
"""I analyzed feature importance and found that customers without phone service, those using fiber internet,
 and those paying via electronic check had higher churn probability, 
indicating that service engagement and payment behavior are strong churn indicators."""